import csv
import random
import subprocess
import xml.etree.ElementTree as ET
import os

# CONFIGURATION #

# Raw car emmission data.
CSV = "carData.csv"

# File holding formatted car types from CSV
VTYPES = "vtypes.xml"

# Random trips generated by randomTrips.py
TRIPS = "random.trips.xml"

# SUMO Network Files
CUSTOM_TRIPS_FILE = "custom.trips.xml"
ROUTES_FILE = "custom.rou.xml"
NET_FILE = "net.net.xml"

SIM_END = 1000

# Step One: Generate vtypes.xml from CSV #

def generate_vtypes(csv_file, vtypes_file):
    
    # Opening up CSV File, then looping through each row and pulling needed data.
    with open(csv_file) as f:
        reader = csv.DictReader(f)
        vtypes = []
        for i, row in enumerate(reader):
            # Appending vtype_id to keep unique.
            vtype_id = row.get("vehicle_type", "car") + f"_{i}"
            emission = row.get("emmissionClass", "HBEFA3/PC_G_EU4")
            max_speed = row.get("maxSpeed", "33")
            length = row.get("length", "5.0")

            vtypes.append(f'<vType id="{vtype_id}" vClass="passenger" '
                          f'emissionClass="{emission}" maxSpeed="{max_speed}" length="{length}"/>')
    
    # Writing file to VTYPES.
    with open(vtypes_file, "w") as f:
        f.write("<vTypeDistribution id=\"customTypes\">\n")
        for v in vtypes:
            f.write("  " + v + "\n")
        f.write("</vTypeDistribution>\n")

# Step two: Call randomTrips.py #
def run_random_trips(net_file,trips_file, sim_end):

    # For simplicity purposes, I included the randomTrips.py file within this rev so
    # adding environment variables is not needed.

    # random_trips = os.path.join(os.environ["SUMO_HOME"], "tools", "randomTrips.py")
    subprocess.run([
        "python", "randomTrips.py",
        "-n", net_file,
        "-e", str(sim_end),
        "-o", trips_file,
        "--seed", "42"
    ], check=True)

    if not os.path.exists(trips_file):
        raise FileNotFoundError(f"Trips file {trips_file} not found after running randomTrips.")

# Step 3: Rewrite trips with random vtypes #
def assign_vtypes(trips_file, vtypes_file, custom_trips_file):
    
    # parse vtypes
    vtypes = []
    tree = ET.parse(vtypes_file)
    root = tree.getroot()
    for v in root.findall("vType"):
        vtypes.append(v.attrib["id"])

    # parse trips
    trips_tree = ET.parse(trips_file)
    trips_root = trips_tree.getroot()

    for trip in trips_root.findall("trip"):
        trip.set("type", random.choice(vtypes))

    trips_tree.write(custom_trips_file)

# Step Four: Convert trips to routes #
def run_duarouter(net_file, custom_trips_file, routes_file, vtypes_file):
    
    subprocess.run([
        "duarouter",
        "-n", net_file,
        "-t", custom_trips_file,
        "-o", routes_file,
        "--additional-files", vtypes_file
    ])



def generate_trips(csv_file, net_file, sim_end=1000):
    print("Starting trip generator.")
    print("Generating vtypes.xml...")
    generate_vtypes(csv_file, "vtypes.xml")

    print("Running randomTrips.py...")
    run_random_trips(net_file, "random.trips.xml", sim_end)

    print("Assigning custom vtypes...")
    assign_vtypes("random.trips.xml", "vtypes.xml", "custom.trips.xml")

    print("Running duarouter...")
    run_duarouter(net_file, "custom.trips.xml", "custom.rou.xml", "vtypes.xml")

    print("Finished!")
    return "custom.rou.xml", "vtypes.xml"


if __name__ == "__main__":
    print("Starting trip generator.")
    print("Generating vtypes.xml...")
    generate_vtypes(CSV, VTYPES)

    print("Running randomTrips.py...")
    run_random_trips(NET_FILE, TRIPS, SIM_END)

    print("Assigning custom vtypes...")
    assign_vtypes(TRIPS, VTYPES, CUSTOM_TRIPS_FILE)

    print("Running duarouter...")
    run_duarouter(NET_FILE, CUSTOM_TRIPS_FILE, ROUTES_FILE, VTYPES)

    print("Finished!")

